version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bankarstvo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bankarstvo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pexample"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # Keycloak Auth Server
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: bankarstvo-keycloak
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "3790:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command:
      - "start-dev"
      - "--import-realm"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: