name: Continuous Deployment
on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install MySQL Server
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
        sudo mysql -e "FLUSH PRIVILEGES;"
    - name: Install Flyway
      run: |
        echo "Downloading Flyway"
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.10.0/flyway-commandline-7.10.0-linux-x64.tar.gz | tar xvz
        echo "Installing Flyway"
        sudo ln -s `pwd`/flyway-7.10.0/flyway /usr/local/bin
    - name: Run Flyway migrations
      run: |
        echo "Running Flyway migrations"
        flyway -url=jdbc:mysql://localhost:3306/banking_app -user=root -password=${{ secrets.MYSQL_ROOT_PASSWORD }} -locations=filesystem:sql/migrations migrate
    - name: Install dependencies
      run: |
        npm install
    - name: Build project
      run: |
        npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Python dependencies
      run: |
        echo "Upgrading pip"
        python -m pip install --upgrade pip
        echo "Installing dependencies from requirements.txt"
        pip install -r requirements.txt
    - name: Run tests
      run: |
        echo "Running tests"
        pytest

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install MySQL Server
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
        sudo mysql -e "FLUSH PRIVILEGES;"
    - name: Install Flyway
      run: |
        echo "Downloading Flyway"
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.10.0/flyway-commandline-7.10.0-linux-x64.tar.gz | tar xvz
        echo "Installing Flyway"
        sudo ln -s `pwd`/flyway-7.10.0/flyway /usr/local/bin
    - name: Run Flyway migrations
      run: |
        echo "Running Flyway migrations"
        flyway -url=jdbc:mysql://localhost:3306/banking_app -user=root -password=${{ secrets.MYSQL_ROOT_PASSWORD }} -locations=filesystem:sql/migrations migrate
    - name: Install dependencies
      run: |
        npm install
    - name: Build project
      run: |
        npm run build
    - name: Deploy to Staging
      run: |
        echo "Deploying to Staging"
        # Add your deployment script/command here

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install MySQL Server
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
        sudo mysql -e "FLUSH PRIVILEGES;"
    - name: Install Flyway
      run: |
        echo "Downloading Flyway"
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.10.0/flyway-commandline-7.10.0-linux-x64.tar.gz | tar xvz
        echo "Installing Flyway"
        sudo ln -s `pwd`/flyway-7.10.0/flyway /usr/local/bin
    - name: Run Flyway migrations
      run: |
        echo "Running Flyway migrations"
        flyway -url=jdbc:mysql://localhost:3306/banking_app -user=root -password=${{ secrets.MYSQL_ROOT_PASSWORD }} -locations=filesystem:sql/migrations migrate
    - name: Install dependencies
      run: |
        npm install
    - name: Build project
      run: |
        npm run build
    - name: Deploy to Production
      run: |
        echo "Deploying to Production"
        # Add your deployment script/command here
