name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_DATABASE: banking_app
  DB_USER: root
  DB_PASSWORD: root

jobs:
  setup-mysql:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

  install-dependencies:
    runs-on: ubuntu-20.04
    needs: setup-mysql
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  run-tests:
    runs-on: ubuntu-20.04
    needs: install-dependencies
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        pytest
