name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install MySQL Server
      run: |
        echo "Updating package list"
        sudo apt-get update
        echo "Installing MySQL Server"
        sudo apt-get install -y mysql-server
        echo "Starting MySQL Service"
        sudo systemctl start mysql
        echo "Printing MySQL default user and password from /etc/mysql/debian.cnf"
        sudo cat /etc/mysql/debian.cnf
        echo "Configuring MySQL for passwordless root access"
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket;"
        sudo mysql -e "FLUSH PRIVILEGES;"
        echo "Restarting MySQL Service"
        sudo systemctl restart mysql
        echo "Checking MySQL Service Status"
        sudo systemctl status mysql
        echo "Listing MySQL users"
        sudo mysql -u root -e "SELECT User, Host FROM mysql.user;"
        echo "Creating database for tests"
        sudo mysql -u root -e "CREATE DATABASE banking_app;"
        echo "Creating tables and inserting dummy data"
        sudo mysql -u root -e "
          CREATE TABLE Users (
            user_id INT AUTO_INCREMENT PRIMARY KEY,
            username VARCHAR(50) NOT NULL,
            email VARCHAR(100) NOT NULL,
            account_created DATETIME NOT NULL,
            last_login DATETIME NOT NULL
          );
          CREATE TABLE accounts (
            account_id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL,
            account_name VARCHAR(50) NOT NULL,
            account_type VARCHAR(50) NOT NULL,
            currency_code VARCHAR(3) NOT NULL,
            balance DECIMAL(10, 2) NOT NULL,
            FOREIGN KEY (user_id) REFERENCES Users(user_id)
          );
          CREATE TABLE transactions (
            transaction_id INT AUTO_INCREMENT PRIMARY KEY,
            account_id INT NOT NULL,
            amount DECIMAL(10, 2) NOT NULL,
            transaction_type VARCHAR(50) NOT NULL,
            transaction_date DATETIME NOT NULL,
            FOREIGN KEY (account_id) REFERENCES accounts(account_id)
          );
          INSERT INTO Users (username, email, account_created, last_login) VALUES
            ('test_user', 'test_user@example.com', '2022-01-01 00:00:00', '2022-01-02 00:00:00');
          INSERT INTO accounts (user_id, account_name, account_type, currency_code, balance) VALUES
            (1, 'Test Account', 'checking', 'USD', 1000.00);
          INSERT INTO transactions (account_id, amount, transaction_type, transaction_date) VALUES
            (1, 100.00, 'deposit', '2022-01-03 00:00:00');
        "
    - name: Install Flyway
      run: |
        echo "Downloading Flyway"
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.10.0/flyway-commandline-7.10.0-linux-x64.tar.gz | tar xvz
        echo "Installing Flyway"
        sudo ln -s `pwd`/flyway-7.10.0/flyway /usr/local/bin
    - name: Run Flyway migrations
      run: |
        echo "Running Flyway migrations"
        flyway -url=jdbc:mysql://localhost:3306/banking_app -user=root -password= -locations=filesystem:sql/migrations migrate
    - name: Install dependencies
      run: |
        echo "Upgrading pip"
        python -m pip install --upgrade pip
        echo "Installing dependencies from requirements.txt"
        pip install -r requirements.txt
    - name: Run tests
      run: |
        echo "Running tests"
        pytest
    - name: Run linting
      run: |
        echo "Installing npm packages"
        npm install
        echo "Running linting"
        npm run lint
