name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Upgrade to Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MySQL
      env:
        MYSQL_ROOT_PASSWORD: root_password  # Replace with your desired root password
        MYSQL_DATABASE: banking_app
        MYSQL_USER: ikokalovic
        MYSQL_PASSWORD: Mikrovela1!
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${{ env.MYSQL_ROOT_PASSWORD }}';"
        sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.MYSQL_DATABASE }};"
        sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE USER IF NOT EXISTS '${{ env.MYSQL_USER }}'@'localhost' IDENTIFIED BY '${{ env.MYSQL_PASSWORD }}';"
        sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${{ env.MYSQL_DATABASE }}.* TO '${{ env.MYSQL_USER }}'@'localhost';"
        sudo mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h"localhost" --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Set up Flyway
      run: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.11.4/flyway-commandline-7.11.4-linux-x64.tar.gz | tar xvz
        sudo ln -s `pwd`/flyway-7.11.4/flyway /usr/local/bin
        flyway -configFiles=tests/flyway.conf migrate

    - name: Run tests
      env:
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        MYSQL_USER: ikokalovic
        MYSQL_PASSWORD: Mikrovela1!
        MYSQL_DATABASE: banking_app
      run: |
        pytest

    - name: Run linting
      run: |
        npm install
        npm run lint
