name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: banking_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_DATABASE: banking_app
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "$DB_HOST" --silent; do
          echo 'waiting for mysql to be connectable...'
          sleep 5
        done

  install-dependencies:
    runs-on: ubuntu-20.04
    needs: setup-mysql

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

  run-tests:
    runs-on: ubuntu-20.04
    needs: install-dependencies

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        python -m pytest
