name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MySQL Server and Client
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server mysql-client
        sudo systemctl start mysql
        sleep 20  # Wait for MySQL to fully start up

    - name: Create User and Database
      run: |
        sudo mysql -e "CREATE USER 'ci_user'@'127.0.0.1' IDENTIFIED BY '${{ secrets.MYSQL_CI_USER_PASSWORD }}';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'ci_user'@'127.0.0.1' WITH GRANT OPTION;"
        sudo mysql -e "FLUSH PRIVILEGES;"
        sudo mysql -u ci_user -p${{ secrets.MYSQL_CI_USER_PASSWORD }} -e "CREATE DATABASE banking_app;"

  run-flyway:
    runs-on: ubuntu-latest
    needs: setup-mysql
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Flyway
      run: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.10.0/flyway-commandline-7.10.0-linux-x64.tar.gz | tar xvz
        sudo ln -s `pwd`/flyway-7.10.0/flyway /usr/local/bin

    - name: Run Flyway migrations
      run: |
        flyway -url=jdbc:mysql://127.0.0.1:3306/banking_app -user=ci_user -password=${{ secrets.MYSQL_CI_USER_PASSWORD }} -locations=filesystem:sql/migrations migrate

  install-dependencies:
    runs-on: ubuntu-latest
    needs: run-flyway
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        pytest
