name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install MySQL Server
      run: |
        echo "Updating package list"
        sudo apt-get update
        echo "Installing MySQL Server"
        sudo apt-get install -y mysql-server
        echo "Starting MySQL Service"
        sudo systemctl start mysql
        echo "Checking MySQL Service Status"
        sudo systemctl status mysql
        echo "Listing MySQL users"
        sudo mysql -e "SELECT User, Host FROM mysql.user;"
        echo "Disabling password for root user"
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'auth_socket';"
        echo "Flushing MySQL privileges"
        sudo mysql -e "FLUSH PRIVILEGES;"
        echo "MySQL setup completed"

    - name: Install dependencies
      run: |
        echo "Upgrading pip"
        python -m pip install --upgrade pip
        echo "Installing dependencies from requirements.txt"
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "Running tests"
        pytest

    - name: Run linting
      run: |
        echo "Installing npm packages"
        npm install
        echo "Running linting"
        npm run lint
