name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: banking_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_DATABASE: banking_app
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "$DB_HOST" --silent; do
          echo 'waiting for mysql to be connectable...'
          sleep 5
        done

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pip install pytest
        python -m pytest

    - name: Run linting
      run: |
        npm install eslint
        npx eslint **/*.js

    - name: Collect errors
      if: failure()
      run: |
        echo "Collecting errors..."
        mkdir -p error_logs
        echo "Error in job: ${{ github.job }}" >> error_logs/errors.log
        echo "Error message: ${{ failure() }}" >> error_logs/errors.log

    - name: Save logs from failed jobs
      if: failure()
      run: |
        mkdir -p pr_failure_logs
        echo "Error in PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}" >> pr_failure_logs/pr_failure.log
        echo "Job: ${{ github.job }}" >> pr_failure_logs/pr_failure.log
        echo "Failure message: ${{ failure() }}" >> pr_failure_logs/pr_failure.log
        echo "Workflow run: ${{ github.event.pull_request.html_url }}" >> pr_failure_logs/pr_failure.log

  code_quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run code quality checks
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pylint **/*.py
          npm install eslint
          npx eslint **/*.js
          npm install stylelint stylelint-scss
          npx stylelint **/*.{css,scss}

  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run security checks
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          bandit -r .

  dependency:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run dependency checks
        run: |
          python -m pip install --upgrade pip
          pip install safety
          safety check
