name: Issue Automation

on:
  issues:
    types: [opened, edited]

jobs:
  automate-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Label issues
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: ".github/labeler.yml"

    - name: Assign issues
      uses: actions/assign-issue@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: 'koke1997'

    - name: Close duplicate issues
      if: contains(github.event.issue.labels.*.name, 'duplicate')
      run: |
        gh issue close ${{ github.event.issue.number }} --comment "This issue is being closed because it is a duplicate."
